---
services:
  vpn:
    profiles: ["vpn", "stack-2"]
    container_name: vpn
    image: qmcgaw/gluetun:${GLUETUN_IMAGE_VERSION}
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_REGIONS=${SERVER_REGIONS}
    ports:
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
      - 9696:9696
    restart: unless-stopped

  transmission:
    profiles: ["tx", "stack-1"]
    container_name: transmission
    image: linuxserver/transmission:${TRANSMISSION_IMAGE_VERSION}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER=${TX_USER}
      - PASS=${TX_PASSWORD}
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - tx-config:/config
      - ${TX_DOWNLOADS}:/downloads
      - tx-watch:/watch
    restart: unless-stopped

  radarr:
    profiles: ["base", "radarr", "stack-1", "stack-2"]
    container_name: radarr
    image: linuxserver/radarr:${RADARR_IMAGE_VERSION}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - ${RADARR_DATA}:/data
    restart: unless-stopped

  sonarr:
    profiles: ["base", "sonarr", "stack-1", "stack-2"]
    container_name: sonarr
    image: linuxserver/sonarr:${SONARR_IMAGE_VERSION}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - sonarr-config:/config
      - ${SONARR_DATA}:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    profiles: ["jackett", "stack-1"]
    container_name: jackett
    image: linuxserver/jackett:${JACKETT_IMAGE_VERSION}
    depends_on:
      - flaresolverr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - jackett-config:/config
      - jackett-blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  flaresolverr:
    profiles: ["jackett", "stack-1"]
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:${FLARESOLVERR_IMAGE_VERSION}
    environment:
      - LOG_LEVEL=${FLARESOLVERR_LOG_LEVEL}
      - TZ=${TZ}
    restart: unless-stopped

  prowlarr:
    profiles: ["prowlarr", "stack-2"]
    container_name: prowlarr
    image: linuxserver/prowlarr:${PROWLARR_IMAGE_VERSION}
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - prowlarr-config:/config
    restart: unless-stopped

  jellyfin:
    profiles: ["base", "jelly", "stack-1", "stack-2"]
    container_name: jellyfin
    image: linuxserver/jellyfin:${JELLYFIN_IMAGE_VERSION}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - ${JELLYFIN_CONFIG}:/config
      - ${JELLYFIN_DATA}:/data
    networks:
      iot-shared-macvlan:
        ipv4_address: ${JELLYFIN_IP}
    restart: unless-stopped

volumes:
  radarr-config:
  sonarr-config:
  jackett-config:
  jackett-blackhole:
  prowlarr-config:
  jellyfin-config:
  tx-config:
  tx-watch:

networks:
  iot-shared-macvlan:
    external: true
