---
- include_tasks: server_bootstrap.yml
  tags:
    - bootstrap
- include_tasks: remove_snap.yml
- include_tasks: add_user.yml
- include_tasks: casaos.yml
  tags:
    - casaos

# TODO
#  - name: import zpools
  # zpool import ****pool -f
  # if possible, check if zsf and zpool are fine
#  - name: Configure Docker with the zfs storage driver
