---
# vars file for samba
WORKDIR: /burkpool/deployments/samba_server
SAMBA_NAME: burkeng
SHARE_1_NAME: burkeng
SHARE_1_PATH: /storage
SHARE_2_NAME: media_files
SHARE_2_PATH: /storage_media
SAMBA_USER: georgiev
SAMBA_GROUP: smb
SAMBA_PASSWORD: 4e6mqnaVoda
SAMBA_UID: 1000
SAMBA_GID: 1000
SAMBA_1_PATH: /burkpool/samba
SAMBA_2_PATH: /storage/media_files
