services:
  pihole:
    container_name: pihole
    image: ghcr.io/valyo/docker-pihole-unbound:${IMAGE_VERSION}
    hostname: ${HOSTNAME}
    domainname: ${PIHOLE_DOMAIN}
    dns: 127.0.0.1
    environment:
      FTLCONF_LOCAL_IPV4: ${FTLCONF_LOCAL_IPV4}
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${WEBPASSWORD}
      REV_SERVER: ${REV_SERVER}
      REV_SERVER_TARGET: ${REV_SERVER_TARGET}
      REV_SERVER_DOMAIN: ${REV_SERVER_DOMAIN}
      REV_SERVER_CIDR: ${REV_SERVER_CIDR}
      DNS1: ${PIHOLE_DNS_} # Our Unbound server
      DNS2: ${PIHOLE_DNS_} # Our Unbound server
      DNSSEC: "true" # Enable DNSSEC
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      FTLCONF_misc_dnsmasq_lines: no-0x20-encode
    cap_add:
      - SYS_TIME
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    networks:
      home:
        ipv4_address: ${FTLCONF_LOCAL_IPV4}
    restart: unless-stopped
volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

networks:
  home:
    driver: macvlan
    driver_opts:
      parent: ${DOCKER_HOST_NIC}
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK_SUBNET}
          gateway: ${DOCKER_NETWORK_GATEWAY}
