services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:${IMAGE_VERSION}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      homeassistant:
        ipv4_address: ${CONTAINER_IP}
    restart: unless-stopped

networks:
  homeassistant:
    driver: macvlan
    driver_opts:
      parent: ${DOCKER_HOST_NIC_VLAN30}
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}
