services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:${IMAGE_VERSION}
    user: "${HOMEASSISTANT_UID}:${HOMEASSISTANT_GID}"
    volumes:
      - ./ha_config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      homeassistant:
        ipv4_address: ${CONTAINER_IP}
    restart: unless-stopped

networks:
  homeassistant:
    driver: macvlan
    driver_opts:
      parent: ${DOCKER_HOST_NIC_VLAN30}
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}
